var searchData=
[
  ['game_0',['Game',['../GreedySnakeBattleGameExternalInterface_8h.html#autotoc_md9',1,'About Greedy Snake Battle Game'],['../GreedySnakeBattleGameExternalInterface_8h.html#autotoc_md33',1,'About Greedy Snake Battle Game']]],
  ['game_20controls_1',['Game Controls',['../index.html#autotoc_md74',1,'']]],
  ['game_20elements_2',['Game Elements',['../index.html#autotoc_md75',1,'']]],
  ['game_20external_20interface_3',['Greedy Snake Battle Game External Interface',['../GSnakeBGEI.html',1,'']]],
  ['game_20features_4',['Game Features',['../index.html#autotoc_md73',1,'']]],
  ['game_20flow_5',['Game Flow',['../index.html#autotoc_md76',1,'']]],
  ['game_20interface_6',['Game Interface',['../index.html#autotoc_md80',1,'']]],
  ['game_20running_20process_20and_20frame_7',['Game running process and frame',['../GreedySnakeBattleGameExternalInterface_8h.html#autotoc_md11',1,'Game running process and frame'],['../GreedySnakeBattleGameExternalInterface_8h.html#autotoc_md35',1,'Game running process and frame']]],
  ['game_20settings_8',['Greedy Snake Battle Game Settings',['../group__SetConfig.html',1,'']]],
  ['gameallrunningdata_9',['GameAllRunningData',['../structGameAllRunningData.html',1,'GameAllRunningData'],['../GameAllRunningData_8h.html#afd29c49c613e516a1a983ab60a5cccfb',1,'GameAllRunningData:&#160;GameAllRunningData.h']]],
  ['gameallrunningdata_2eh_10',['GameAllRunningData.h',['../GameAllRunningData_8h.html',1,'']]],
  ['gameapplicationstartuprelated_2ec_11',['gameApplicationStartupRelated.c',['../gameApplicationStartupRelated_8c.html',1,'']]],
  ['gameapplicationstartuprelated_2eh_12',['gameApplicationStartupRelated.h',['../gameApplicationStartupRelated_8h.html',1,'']]],
  ['gameconfig_13',['GameConfig',['../structGameConfig.html',1,'GameConfig'],['../GameConfig_8h.html#aa64fdb8a1b9c72973d80bb0dd73c757e',1,'GameConfig:&#160;GameConfig.h']]],
  ['gameconfig_2eh_14',['GameConfig.h',['../GameConfig_8h.html',1,'']]],
  ['gameinterfacepainting_15',['gameInterfacePainting',['../painting_8h.html#ac021fc2dc4e594eb7de811c66fac7528',1,'gameInterfacePainting(GameAllRunningData const *const data):&#160;painting.c'],['../painting_8c.html#ac021fc2dc4e594eb7de811c66fac7528',1,'gameInterfacePainting(GameAllRunningData const *const data):&#160;painting.c']]],
  ['gameintroduction_16',['gameIntroduction',['../userInterfaceBeforeGameStarts_8h.html#aa262db24645e5922376802ff5d1c661e',1,'gameIntroduction():&#160;userInterfaceBeforeGameStarts.c'],['../userInterfaceBeforeGameStarts_8c.html#aa262db24645e5922376802ff5d1c661e',1,'gameIntroduction():&#160;userInterfaceBeforeGameStarts.c']]],
  ['gamemainlogic_2ec_17',['gameMainLogic.c',['../gameMainLogic_8c.html',1,'']]],
  ['gamemainlogic_2eh_18',['gameMainLogic.h',['../gameMainLogic_8h.html',1,'']]],
  ['gameoverpainting_19',['gameOverPainting',['../painting_8h.html#ad103610cd85f989253e54410b88528fc',1,'gameOverPainting(GameAllRunningData *data):&#160;painting.c'],['../painting_8c.html#ad103610cd85f989253e54410b88528fc',1,'gameOverPainting(GameAllRunningData *data):&#160;painting.c']]],
  ['gamesetconfiguration_2ec_20',['gameSetConfiguration.c',['../gameSetConfiguration_8c.html',1,'']]],
  ['gamesetconfiguration_2eh_21',['gameSetConfiguration.h',['../gameSetConfiguration_8h.html',1,'']]],
  ['gamestartuploading_22',['gameStartupLoading',['../userInterfaceBeforeGameStarts_8h.html#a4c54ea2f9428155f24727b7abc84d05a',1,'gameStartupLoading():&#160;userInterfaceBeforeGameStarts.c'],['../userInterfaceBeforeGameStarts_8c.html#a4c54ea2f9428155f24727b7abc84d05a',1,'gameStartupLoading():&#160;userInterfaceBeforeGameStarts.c']]],
  ['gamestartuprelated_2ec_23',['gameStartupRelated.c',['../gameStartupRelated_8c.html',1,'']]],
  ['gamestartuprelated_2eh_24',['gameStartupRelated.h',['../gameStartupRelated_8h.html',1,'']]],
  ['get_5fbuffered_5finput_25',['get_buffered_input',['../group__OSAdapt.html#gaea6d5018cf2471abec242ffa12822315',1,'snakeFullCompat.c']]],
  ['get_5funbuffered_5finput_26',['get_unbuffered_input',['../group__OSAdapt.html#ga8394878343d9c77a7c108b714fc1e8ee',1,'snakeFullCompat.c']]],
  ['globalvariable_2ec_27',['globalVariable.c',['../globalVariable_8c.html',1,'']]],
  ['globalvariable_2eh_28',['globalVariable.h',['../globalVariable_8h.html',1,'']]],
  ['gpg_20strong_29',['&lt;strong&gt;Install GPG&lt;/strong&gt;',['../index.html#autotoc_md60',1,'']]],
  ['greedy_20snake_20battle_30',['Greedy Snake Battle',['../index.html',1,'']]],
  ['greedy_20snake_20battle_20game_31',['Greedy Snake Battle Game',['../GreedySnakeBattleGameExternalInterface_8h.html#autotoc_md9',1,'About Greedy Snake Battle Game'],['../GreedySnakeBattleGameExternalInterface_8h.html#autotoc_md33',1,'About Greedy Snake Battle Game']]],
  ['greedy_20snake_20battle_20game_20external_20interface_32',['Greedy Snake Battle Game External Interface',['../GSnakeBGEI.html',1,'']]],
  ['greedy_20snake_20battle_20game_20settings_33',['Greedy Snake Battle Game Settings',['../group__SetConfig.html',1,'']]],
  ['greedysnakebattlegameexternalinterface_34',['GreedySnakeBattleGameExternalInterface',['../GreedySnakeBattleGameExternalInterface_8c.html#a07b30632007b10dc759236858d9e57f1',1,'GreedySnakeBattleGameExternalInterface(int isBlockRunning):&#160;GreedySnakeBattleGameExternalInterface.c'],['../GreedySnakeBattleGameExternalInterface_8h.html#a07b30632007b10dc759236858d9e57f1',1,'GreedySnakeBattleGameExternalInterface(int isBlockRunning):&#160;GreedySnakeBattleGameExternalInterface.c']]],
  ['greedysnakebattlegameexternalinterface_2ec_35',['GreedySnakeBattleGameExternalInterface.c',['../GreedySnakeBattleGameExternalInterface_8c.html',1,'']]],
  ['greedysnakebattlegameexternalinterface_2eh_36',['GreedySnakeBattleGameExternalInterface.h',['../GreedySnakeBattleGameExternalInterface_8h.html',1,'']]],
  ['group_37',['Operating system adaptation function group',['../group__OSAdapt.html',1,'']]],
  ['guidelines_38',['Code Style Summary &amp; Contribution Guidelines',['../index.html#autotoc_md97',1,'']]]
];
